### ISSUE TITLE
helmbank file

### ISSUE THREAD

**Issue by drount** [jpriebe/qub1t-helm-patches#1]
Hello, 
thanks for the pack. 
For some reason when I install the .helmpack the patches do not appear in the browse window neither are they in the patches folder. I needed to download your individual .helm files.

Do you know why?

**Comment by jpriebe** [comment]
Not sure what happened.  I believe those helmbank files are just zip files, so you could always try unzipping (if you're on Windows, just rename it to qub1t.helmbank.zip -- if it doesn't unpack, then something's wrong with the format).

At any rate, you are right -- it wasn't loading into Helm.  So I loaded the latest patches into Helm and re-exported.  I verified that if I removed the qub1t patches from helm, I could re-import them.

One more bit of info -- the helm patches are just stored on the file system.  In Windows, it's in your Documents/Helm directory (not entirely sure where they're stored on Linux or MacOS).  So you could always clone the repo and move it to that directory with the other patches, and you should be good to go.

But please give the new helmbank file a try and let me know if it works for you!

**Comment by drount** [comment]
Hey, 

they load now! Thanks for answering
